"""FastAPI wrapper for hydro-irrigation — auto-generated by stack_migrate_hydro.py.

Expose original Python logic without touching Streamlit or src/ modules.
Run:
    uv run uvicorn api:app --host 127.0.0.1 --port 8615 --reload

Requires python-multipart for file upload:
    uv add python-multipart
"""
from __future__ import annotations

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response

app = FastAPI(title="hydro-irrigation-api", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3115",
        "http://127.0.0.1:3115",
        "https://hydro-irrigation.tianlizeng.cloud",
    ],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


@app.get("/api/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/api/meta")
def meta_info() -> dict:
    return {
        "name": "irrigation",
        "title": "灌溉需水",
        "icon": "🌾",
        "description": "水稻+旱地灌溉需水量水平衡计算",
        "version": "1.0.0",
    }


@app.post("/api/compute")
async def compute(file: UploadFile = File(...)) -> Response:
    """Placeholder — returns 501 until the per-plugin logic is wired up.

    TODO — replace this stub with real logic:
      1. Find the Streamlit compute function in ~/Dev/hydro-irrigation/app.py
         (look for something like `run_calculation_from_xlsx`, or the
         body of the "开始计算" button handler).
      2. Rewrite it here without `import streamlit` — read the upload
         via `await file.read()`, call the `src.*` core modules, and
         return `Response(content=xlsx_bytes, media_type="application/...")`.
      3. If the computation returns CJK metadata (e.g. reservoir names),
         URL-encode it into response headers:
             from urllib.parse import quote
             headers={ "X-Foo": quote(str(foo)), ... }
      4. Expose those headers to the browser via
             "Access-Control-Expose-Headers": "X-Foo, ..."
    """
    raise HTTPException(
        status_code=501,
        detail=(
            "/api/compute 尚未实现 — 在 ~/Dev/hydro-irrigation/api.py 里替换占位版本，"
            "或参考 ~/Dev/hydro-reservoir/api.py 的 `_run_reservoir(...)` 模式。"
        ),
    )
